-- MySQL Script generated by MySQL Workbench
-- Thu Mar  5 14:15:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vaccination
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vaccination` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vaccination` ;

-- -----------------------------------------------------
-- Table `vaccination`.`drug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccination`.`drug` (
  `drug_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `MNN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`drug_id`),
  UNIQUE INDEX `drug_id_UNIQUE` (`drug_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vaccination`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccination`.`hibernate_sequence` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vaccination`.`medical_institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccination`.`medical_institution` (
  `medical_institution_code` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `address` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`medical_institution_code`),
  UNIQUE INDEX `medical_institution_id_UNIQUE` (`medical_institution_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vaccination`.`medical_worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccination`.`medical_worker` (
  `medical_worker_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `medical_institution_code` INT NOT NULL,
  PRIMARY KEY (`medical_worker_id`),
  UNIQUE INDEX `medical_worker_id_UNIQUE` (`medical_worker_id` ASC) VISIBLE,
  INDEX `placeWorkerFK_idx` (`medical_institution_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 113
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vaccination`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccination`.`patient` (
  `patient_id` INT NOT NULL,
  `SNILS` BIGINT NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `medical_institution_code` INT NULL DEFAULT NULL,
  `birth_date` DATE NOT NULL,
  PRIMARY KEY (`patient_id`),
  UNIQUE INDEX `SNILS_UNIQUE` (`SNILS` ASC) VISIBLE,
  UNIQUE INDEX `patient_id_UNIQUE` (`patient_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vaccination`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccination`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NULL DEFAULT 'USER',
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `medical_worker_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 79
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vaccination`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccination`.`user_role` (
  `iduser_role` INT NOT NULL,
  `user_role` VARCHAR(45) NULL DEFAULT 'USER',
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`iduser_role`),
  INDEX `sdf_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `sdf`
    FOREIGN KEY (`user_id`)
    REFERENCES `vaccination`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vaccination`.`vaccination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vaccination`.`vaccination` (
  `vaccination_id` INT NOT NULL AUTO_INCREMENT,
  `SNILS` BIGINT NOT NULL,
  `consent` BIT(1) NOT NULL,
  `vac_date` DATE NOT NULL,
  `drug_id` INT NOT NULL,
  `medical_worker_id` INT NOT NULL,
  PRIMARY KEY (`vaccination_id`),
  UNIQUE INDEX `idvaccination_id_UNIQUE` (`vaccination_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
